USE [master]
GO

/****** Object:  Database [blogs]    Script Date: 09/10/2024 12:39:38 p. m. ******/
CREATE DATABASE [blogs]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'blog', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\blog.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'blog_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\blog_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [blogs].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [blogs] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [blogs] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [blogs] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [blogs] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [blogs] SET ARITHABORT OFF 
GO

ALTER DATABASE [blogs] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [blogs] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [blogs] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [blogs] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [blogs] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [blogs] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [blogs] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [blogs] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [blogs] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [blogs] SET  DISABLE_BROKER 
GO

ALTER DATABASE [blogs] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [blogs] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [blogs] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [blogs] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [blogs] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [blogs] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [blogs] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [blogs] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [blogs] SET  MULTI_USER 
GO

ALTER DATABASE [blogs] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [blogs] SET DB_CHAINING OFF 
GO

ALTER DATABASE [blogs] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [blogs] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [blogs] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [blogs] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [blogs] SET QUERY_STORE = OFF
GO

ALTER DATABASE [blogs] SET  READ_WRITE 
GO


